sudo: false

language: android

android:
  components:
    - build-tools-23.0.1
    - android-23

branches:
  only:
    - master
    - android_develop

jdk: openjdk7

notifications:
  email: false

install: gradle clean build

script: gradle check
